# Computer Vision Fall 2022
# Assignment 1
# Author: Pablo Ruiz

all: program1 program2 program3

program1: Program_1.cpp
	g++ -g Program_1.cpp -o Program_1.out

program2: Program_2.cpp
	g++ -g Program_2.cpp -o Program_2.out

program3: Program_3.cpp
	g++ -g Program_3.cpp -o Program_3.out